<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Serve.Tests</RootNamespace>
    <AssemblyName>Mau.Serve.Tests</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Serve\Mau.Serve.csproj" />
    <ProjectReference Include="..\Mau.Development\Mau.Development.csproj" />
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
  </ItemGroup>

</Project>
