<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Cli</RootNamespace>
    <AssemblyName>Mau</AssemblyName>
    <Version>3.21.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
    <ProjectReference Include="..\Mau.Translator\Mau.Translator.csproj" />
    <ProjectReference Include="..\Mau.Runtime\Mau.Runtime.csproj" />
    <ProjectReference Include="..\Mau.Development\Mau.Development.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.11.0" />
  </ItemGroup>

</Project>
