<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Bricks</RootNamespace>
    <AssemblyName>Mau.Bricks.Data</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
  </ItemGroup>

</Project>
