<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Mau.Translator</RootNamespace>
    <AssemblyName>Mau.Translator</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
    <ProjectReference Include="..\Mau.Runtime\Mau.Runtime.csproj" />
  </ItemGroup>

</Project>
