<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CatHome4.Contracts</RootNamespace>
    <AssemblyName>CatHome4.Contracts</AssemblyName>
  </PropertyGroup>

</Project>
