<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CatHome4.Admin</RootNamespace>
    <AssemblyName>CatHome4.Admin</AssemblyName>
    <Version>1.01.001</Version>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CatHome4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mau\Mau.Runtime\Mau.Runtime.csproj" />
    <ProjectReference Include="..\..\Mau\Mau.Providers\Mau.Providers.csproj" />
    <ProjectReference Include="..\CatHome4.Contracts\CatHome4.Contracts.csproj" />
    <ProjectReference Include="..\CatHome4.Core\CatHome4.Core.csproj" />
    <ProjectReference Include="..\CatHome4.Http\CatHome4.Http.csproj" />
    <ProjectReference Include="..\CatHome4.QQ\CatHome4.QQ.csproj" />
  </ItemGroup>

</Project>
