<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Cli</RootNamespace>
    <AssemblyName>Mau</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
    <ProjectReference Include="..\Mau.Translator\Mau.Translator.csproj" />
    <ProjectReference Include="..\Mau.Bricks.Standard\Mau.Bricks.Standard.csproj" />
  </ItemGroup>

</Project>
