<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CatHome4.Http</RootNamespace>
    <AssemblyName>CatHome4.Http</AssemblyName>
    <Version>1.01.000</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mau\Mau.Runtime\Mau.Runtime.csproj" />
    <ProjectReference Include="..\CatHome4.Contracts\CatHome4.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
