<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Bricks.Tests</RootNamespace>
    <AssemblyName>Mau.Bricks.Tests</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Bricks.Standard\Mau.Bricks.Standard.csproj" />
    <ProjectReference Include="..\Mau.Bricks.Data\Mau.Bricks.Data.csproj" />
    <ProjectReference Include="..\Mau.Bricks.Text\Mau.Bricks.Text.csproj" />
    <ProjectReference Include="..\Mau.Bricks.Shell\Mau.Bricks.Shell.csproj" />
    <ProjectReference Include="..\Mau.Contracts\Mau.Contracts.csproj" />
  </ItemGroup>

</Project>
