<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Mau.Runtime.Tests</RootNamespace>
    <AssemblyName>Mau.Runtime.Tests</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Mau.Snapshots\expected\FL_FileConvert.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mau.Runtime\Mau.Runtime.csproj" />
    <ProjectReference Include="..\Mau.Bricks.Standard\Mau.Bricks.Standard.csproj" />
  </ItemGroup>

</Project>
